language: php

php:
  - 7.0
  - 5.6

before_install:
  - pecl install xdebug
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - composer install
  - vendor/bin/robo build
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: info@appserver.io
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
